name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      binary: ${{steps.build.outputs.binary}}
      measurements: ${{steps.build.outputs.measurements}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: |
          python3 createMeasurements.py --seed 1234 -r 10000000
      - name: Upload measurement artifact
        uses: actions/upload-artifact@v3
        with:
          name: measurements
          path: ./measurements.txt
          retention-days: 1
      - run:
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"
      - run: |
          make build
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: ./1brc
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: "**"
      - run: ./1brc
      - run: cmp --silent output.txt expected.10mil.1234.txt

  bench:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        attempt: [1, 2, 3, 4, 5]
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: "**"
      - run: |
          time make run > runtime_${{matrix.attempt}}.txt

      - name: Upload the runtime as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: runtimes_${{ matrix.attempt }}
          path: runtime_${{ matrix.attempt }}.txt
          retention-days: 1

  gather-results:
    runs-on: ubuntu-latest
    needs: bench
    steps:
      - name: Download all runtime artifacts
        uses: actions/download-artifact@v3
        with:
          name: "**"
      - name: Combine all runtime results
        run: |
          cat runtime_*.txt > all_runtimes.txt
          echo "All runtimes combined:"
          cat all_runtimes.txt
